### ISSUE TITLE
possible documentation error in make_rarefaction_plots.py

### ISSUE THREAD

**Issue by jairideout** [biocore/qiime#1857]
The following text is in the output of make_rarefaction_plots.py:

"If the lines for some categories do not extend all the way to the right end of the x-axis, that means that at least one of the samples in that category does not have that many samples."

Should this instead be:

"If the lines for some categories do not extend all the way to the right end of the x-axis, that means that at least one of the samples in that category does not have that many **sequences**."

cc @gregcaporaso

**Comment by adamrp** [comment]
I noticed this issue, too, thanks @jairideout!

What I'd really like to see (and this is probably a different issue, but thought I'd raise it here since it's somewhat related and this issue is receiving developer attention currently) is an option to override this behavior. In other words, if samples in a category do not have the minimum number of sequences, then those samples are dropped and the average is calculated over the remaining samples (and in the data table, the `N` is reported). Is there a reason that this is a bad idea, or is it just something that no one has implemented yet?

**Comment by jairideout** [comment]
Thanks @adamrp! Can you please create a new issue for this feature? This issue was just closed.

**Comment by adamrp** [comment]
Sure thing -- that will make sense.

**Comment by jairideout** [comment]
Thanks!
