### ISSUE TITLE
pick_otus.py -m swarm fails without an error

### ISSUE THREAD

**Issue by antgonza** [biocore/qiime#2014]
If we have a regular fna file and pick with swarm, everything seems fine
```bash
$ echo -e '>S1\nAAAAA\n>S2\nAAAA' > seqs.fna
$ pick_otus.py -m swarm -i seqs.fna
$ more swarm_picked_otus/seqs_otus.txt 
denovo0 S2      S1
```
However, if we have  ambiguous nucleotides, this fails without an error
```bash
$ echo -e '>S1\nAAAAAN\n>S2\nAAAA' > seqs.fna
$ pick_otus.py -m swarm -i seqs.fna
$ more swarm_picked_otus/seqs_otus.txt 
```

**Comment by josenavas** [comment]
Thanks @antgonza 
We know that swarm does not work with ambiguous nucleotides. However, I thought that was checked by the code at some point.

@ekopylova there isn't any check/clean up in the burrito-fillings wrapper or QIIME that cleans up those sequences?

**Comment by ekopylova** [comment]
Swarm exits with an error (ex. "Error: Illegal character 'N' in sequence on line 2") when any character other than A/C/G/T/U is encountered. As far as I remember there isn't code in either burrito-fillings or QIIME that checks this error. It's not something we noticed until running Swarm on raw fasta files, since QIIME's split_libraries_fastq filters out sequences with N's (by default). However, this does need to be fixed.

**Comment by gregcaporaso** [comment]
@antgonza, want to work on this one for the release? This might be as simple as adding an ``_accept_exit_status`` method to the swarm application controller (see the old docs [here](http://pycogent.org/examples/application_controller_framework.html?highlight=application#command-lineapplication-cogent-app-util-py) - these are in the process of being ported to the burrito wiki).

**Comment by gregcaporaso** [comment]
@antgonza, if you could take a quick look before we talk tomorrow that'd be ideal as we're going to figure out when to do the burrito/burrito-fillings release tomorrow morning.

**Comment by jairideout** [comment]
Fixed in https://github.com/biocore/burrito-fillings/pull/67
