### ISSUE TITLE
Unsatisfiable package specifications

### ISSUE THREAD

**Issue by sebastian-luna-valero** [biocore/qiime#2050]
Dear All,

I am trying to install qiime with Conda by following the instructions here:
https://anaconda.org/hcc/qiime

However, I get:
```
testing-qiime/bin/conda install -c http://conda.anaconda.org/hcc qiime
Fetching package metadata: ............
Solving package specifications: .
Error: Unsatisfiable package specifications.
Generating hint: 
[      COMPLETE      ]|################################################################################################################################################################################################################| 100%


Hint: 'qiime' has unsatisfiable dependencies (see 'conda info qiime')
```

I am using Conda 3.14 with Python 2.7.10.

Are there any specific channels that I need to include? or could you please point me to a solution?

Best regards,
Sebastian

**Comment by Jorge-C** [comment]
Hi @sebastian-luna-valero! It seems that package was built by the Holland Computing Center, and I don't know the "conda recipe" that they used, but the problem is that installing that package requires certain versions of the dependencies that are not provided in their conda channel.

I'd suggest contacting them to let them know, and please keep us posted here (we have an issue regarding creating an official conda package for qiime [here](https://github.com/biocore/qiime/issues/1759)).

Otherwise, you can install most qiime deps using conda, and then use pip to actually install the latest qiime version. Something like this should work:
```
conda -n create qiime190 pip numpy matplotlib IPython future natsort scipy pandas gdata
source activate qiime190
pip install qiime
```
