### ISSUE TITLE
make_rarefaction_plot.py

### ISSUE THREAD

**Issue by jtremblay** [biocore/qiime#2055]
Dear Qiime community,
I had some trouble running make_rarefaction_plots.py as a PBS job. So briefly, when I run this command:
```
make_rarefaction_plots.py \
  -i ./collated/ \
  -m ./mapping_file.tsv \
  -o ./plots/ \
  --generate_average_tables \
  -s 
```
I get the following error msg:
`: cannot connect to X server localhost:17.0`

In my matplot lib installation I modified the 
`lib/python/matplotlib/mpl-data/matplotlibrc` file and replaced line 38 with `backend      : Agg`
It works fine now.

I tried to add this import/use before importing pyplot, but didn't work:
```
import matplotlib as mpl
mpl.use('Agg')
```

Cheers,

**Comment by moskalenko** [comment]
Put the

from matplotlib import use
use('Agg', warn=False)

at the top of the make_rarefaction_plots.py imports list.

**Comment by chienchi** [comment]
plot_taxa_summary.py has the same error msg and apply the patch above solve the problem.

**Comment by ElDeveloper** [comment]
Personally I've seen this problem when I've been working on a few servers. The general solution is to change the backend (like @jtremblay suggests) to accommodate to the restrictions of the environment, the reason why this shouldn't be changed in the master branch is because projects shouldn't impose what backend needs to be used, this is a task for matplotlib and the end user.

@moskalenko & @chienchi did you try modifying your matplotlibrc file? If you need to find out the location, this should do the trick:

```
python -c 'import matplotlib as m; print m.matplotlib_fname()'
```
