### ISSUE TITLE
test_otu_significance.py is failing in Travis

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/qiime#2078]
This is preventing the tests in #2077 from passing.

```python
======================================================================
FAIL: test_run_correlation_test (__main__.GroupedCorrelationTests)
Test run_correlation_test works.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/workspace/qiime-github-pr/qiime/tests/test_otu_significance.py", line 893, in test_run_correlation_test
    assert_almost_equal(obs_pvals[:-1], exp_bootstrapped_pvals)
  File "/mnt/workspace/qiime-github-pr/anaconda/envs/test_env/lib/python2.7/site-packages/numpy/testing/utils.py", line 474, in assert_almost_equal
    return assert_array_almost_equal(actual, desired, decimal, err_msg)
  File "/mnt/workspace/qiime-github-pr/anaconda/envs/test_env/lib/python2.7/site-packages/numpy/testing/utils.py", line 842, in assert_array_almost_equal
    precision=decimal)
  File "/mnt/workspace/qiime-github-pr/anaconda/envs/test_env/lib/python2.7/site-packages/numpy/testing/utils.py", line 665, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal to 7 decimals

(mismatch 20.0%)
 x: array([ 0.486,  0.046,  0.371,  0.882,  0.438])
 y: array([ 0.486,  0.046,  0.382,  0.882,  0.438])

----------------------------------------------------------------------
Ran 15 tests in 42.885s

FAILED (failures=1)
```

@jairideout did something change when the CI system went down over the weekend?

@wdwvt1 any ideas on this?

I've tried with a few different versions of numpy and scipy in my machine and I can't replicate this problem.

**Comment by antgonza** [comment]
Could hardware be an issue? Will it be OK to se the test to 1 decimal?

**Comment by jairideout** [comment]
@ElDeveloper nothing changed from the downtime over the weekend. Maybe numpy/scipy versions were upgraded recently? The CI system just installs whatever is in setup.py, so it could be grabbing a newer version of one of QIIME's dependencies.

**Comment by jairideout** [comment]
Confirmed that this test was failing before the weekend downtime. [Build 918](http://ci.qiime.org/job/QIIME/918/?) had these tests succeeding and they fail in [build 919](http://ci.qiime.org/job/QIIME/919/?). The `print_qiime_config.py -tf` output from the two runs are exactly the same, so dependency versions and/or QIIME configuration isn't the issue.

**Comment by wdwvt1** [comment]
hmm, this is disconcerting. I remember having trouble with this test in the first place - as evidenced by the comment on lines 883-892, but the discrepancy was smaller than the .011 difference seen at index 2. 

The tests pass on my system as I suspect they do on ya'lls. It looks like on whatever machine travis is running on, 11 evaluations of `x >= y` that are `False` on my system are `True` on that system. 

What machine specific things could cause that? Could it be that a different number of calls to the prng are being used and thus the seed on line 877 no longer accurately places the prng for the bootstraps? This seems unlikely because 4/5 entries being compared have the correct values, which would not likely be true if the seed were off. 

@antgonza - setting to 1 decimal place makes me very uncomfortable, these should evaluate exactly as I am seeding the prng on line 877.

**Comment by antgonza** [comment]
@wdwvt1, what about fixing the seed for the tests so we always get the same values?

**Comment by wdwvt1** [comment]
it is fixed (line 877). the question is - are there differences in the
number of calls to the prng on different systems? i think not, but i am
very ill-qualified to say that.

**Comment by ElDeveloper** [comment]
@wdwvt1 I have no idea what might be causing this.

@jairideout, thanks for having a look, it is at least reassuring to know that this was a problem even before #2077.

All, I've tried a variety of things now and wasn't able to reproduce the bug, here's what I've tried:
- Upgrade numpy/scipy in a virtualenv.
- Downgrade numpy/scipy in a virtualenv.
- Do a full QIIME installation using conda.
- Copying and pasting the commands from qiime-ci https://github.com/qiime/qiime-ci/blob/master/qiime.sh

And the tests still pass in my machine, so I have no idea :scream:

**Comment by ElDeveloper** [comment]
After further looking into this, I was able to reproduce the problem in a conda environment in a linux machine, see the steps below to try it out on your own.

When looking into the differences between the linux environment and the OSX environment, conda is installing openblas in linux, which is not the case in OSX, furthermore that is one of the main differences between [Jenkins' build 918](http://ci.qiime.org/job/QIIME/918/consoleText) and [Jenkins' build 919](http://ci.qiime.org/job/QIIME/919/consoleText).

However, when I compiled numpy and scipy from source in the linux machine and forced it to use the system-wide libraries instead of the precompiled binaries that conda installs, the error persisted.

If if helps at all, the failure is exactly the same, @wdwvt1, any chance the test case can be reworked so it passes both in OSX and in Linux? I can help you do some testing in Linux if you need help!


### with conda in linux

```python
(qiime)yovazquezbaeza:~$ python qiime/tests/test_otu_significance.py 
.......Warning: No metadata in biom table. Won't alter calculations.
......F.
======================================================================
FAIL: test_run_correlation_test (__main__.GroupedCorrelationTests)
Test run_correlation_test works.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "qiime/tests/test_otu_significance.py", line 893, in test_run_correlation_test
    assert_almost_equal(obs_pvals[:-1], exp_bootstrapped_pvals)
  File "/home/yovazquezbaeza/miniconda/envs/qiime/lib/python2.7/site-packages/numpy/testing/utils.py", line 474, in assert_almost_equal
    return assert_array_almost_equal(actual, desired, decimal, err_msg)
  File "/home/yovazquezbaeza/miniconda/envs/qiime/lib/python2.7/site-packages/numpy/testing/utils.py", line 842, in assert_array_almost_equal
    precision=decimal)
  File "/home/yovazquezbaeza/miniconda/envs/qiime/lib/python2.7/site-packages/numpy/testing/utils.py", line 665, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal to 7 decimals

(mismatch 20.0%)
 x: array([ 0.486,  0.046,  0.371,  0.882,  0.438])
 y: array([ 0.486,  0.046,  0.382,  0.882,  0.438])

----------------------------------------------------------------------
Ran 15 tests in 16.020s

FAILED (failures=1)
```

### building from source in linux
```python
(qiime-dev)yovazquezbaeza:~$ python qiime/tests/test_otu_significance.py 
.......Warning: No metadata in biom table. Won't alter calculations.
......F.
======================================================================
FAIL: test_run_correlation_test (__main__.GroupedCorrelationTests)
Test run_correlation_test works.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "qiime/tests/test_otu_significance.py", line 893, in test_run_correlation_test
    assert_almost_equal(obs_pvals[:-1], exp_bootstrapped_pvals)
  File "/home/yovazquezbaeza/miniconda/envs/qiime-dev/lib/python2.7/site-packages/numpy/testing/utils.py", line 454, in assert_almost_equal
    return assert_array_almost_equal(actual, desired, decimal, err_msg)
  File "/home/yovazquezbaeza/miniconda/envs/qiime-dev/lib/python2.7/site-packages/numpy/testing/utils.py", line 811, in assert_array_almost_equal
    header=('Arrays are not almost equal to %d decimals' % decimal))
  File "/home/yovazquezbaeza/miniconda/envs/qiime-dev/lib/python2.7/site-packages/numpy/testing/utils.py", line 644, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal to 7 decimals

(mismatch 20.0%)
 x: array([ 0.486,  0.046,  0.371,  0.882,  0.438])
 y: array([ 0.486,  0.046,  0.382,  0.882,  0.438])

----------------------------------------------------------------------
Ran 15 tests in 5.781s

FAILED (failures=1)
```

---------


### steps to get an env up and running
```bash
wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh
chmod +x Miniconda-latest-Linux-x86_64.sh
./Miniconda-latest-Linux-x86_64.sh -b
export PATH=${HOME}/miniconda/bin/:$PATH
conda create -n qiime-dev scipy numpy matplotlib pandas cython h5py hdf5 pip
source activate qiime-dev
git clone git://github.com/biocore/qiime
pip install qiime
python qiime/tests/test_otu_significance.py
```

**Comment by wdwvt1** [comment]
am over my bandwidth currently - won't be able to help until quals proposal
is done (sept 7th). while i have no idea why that would be failing on
different systems.

i think to solve this we have a pretty straightforward approach: iterate
over new seeds for the prng until one is found that produces the same
results on both of the systems we are failing on then write that seed into
line 877.

**Comment by ElDeveloper** [comment]
@wdwvt1, got it, thanks!

I started going down the rabbit hole. As per @wdwvt1's suggestion I switched the value of the seeds, though that proved to not be useful at all, as the problem doesn't seem to be the random number generator. The problem seems to be the precision that the machines have and there seems to be something special about that third correlation calculation. I think the solution is to change the test data being used in this test case, @wdwvt1, do you know if that third case is an edge case or something much different from the other subsets of the data? I couldn't tell from looking at the input table. Alternatively if there's nothing special about this, then we probably should just change the inputed values.

**Comment by gregcaporaso** [comment]
Hey guys, Thanks for your time on this one. Just wondering if there has been any progress (I'm guessing not) or maybe if there could be now that @wdwvt1 is ABD (congrats @wdwvt1!).

**Comment by ElDeveloper** [comment]
@gregcaporaso, no I have not made any progress on this, from my first pass I couldn't quite find what was going on.

**Comment by wdwvt1** [comment]
hey guys,

i will take a look at this starting tomorrow - thanks for giving it a go
@eldeveloper, i'll ping you and ask questions as i work through.

**Comment by gregcaporaso** [comment]
Awesome, thanks @wdwvt1! It'd be really helpful to figure this out to get QIIME back to passing its tests on Jenkins.  Let me know if I can do anything to help.

**Comment by wdwvt1** [comment]
I did some digging, and I feel like I have isolated the problem but I don't understand it. Someone with more knowledge of floats will be super helpful. 

Setup:

`r*` = correlation coefficient between vectors x and y
`r_i` = correlation coefficient between vectors x and permuted vector y_i

At a high level, the test is failing because there are 3 `r_i`'s that are smaller than anticipated (or compare as smaller than anticipated) on the linux builds. 

When I do the calculations for this specific test on my machine, I find 372 `r_i`'s to be larger than `r*`. On the linux machine, 369 `r_i`'s compare as larger than `r*`.  

Diagnosis:

I forced each `r_i` to be printed at more decimal places than it was stored with in memory 
 on both my mac and on the travis linux build. 
```python
print '%.64f' % val
```

When I compared the linux values produced this way I found that 366/1000 `r_i`'s where greater than/equal to `r*`. 
When I compared the mac values produced this way I found that 366/100 `r_i`'s where greater than/equal to `r*`. 

This made no sense; the test passes (when I am not forcing the values to be displayed at more than their precision) on my mac with 372/1000 `r_i`'s greater than/equal to `r*`.

Suspecting that something was happening with the decimal representations, I checked the `r*` values against the `r_i`'s and found that on my mac (with the more digits than precision), 6 `r_i`'s compare as equal to the `r*`. When I compare the linux generated values, (again with more digits than precision) 3 `r_i`'s compare as equal to the `r*`. 

This makes some sort of sense. The test is failing on linux with 369/1000 `r_i`'s comparing as greater than/equal to `r*`. Somehow, 3 of the 6 `r_i`'s which compare equal to `r*` on the mac are comparing as less than on linux. 

Another fact that might be of importance: the representation of `r*` is different on my mac and on linux. 
```python
r_star_linux = 0.4403759479485386263419854913081508129835128784179687500000000000
r_star_linux.as_integer_ratio()
(3966553910167935, 9007199254740992)
r_star_mac = 0.4403759479485385153196830287924967706203460693359375000000000000
r_star_mac.as_integer_ratio()
(1983276955083967, 4503599627370496)
```
I don't know if it's relevant, but the integer representations of those values have different numbers of bits of precision - 52 for the mac, 53 for linux. 
```python
np.log2(4503599627370496) = 52
np.log2(9007199254740992) = 53
```

**Comment by antgonza** [comment]
Thanks for the detailed explanation. What about testing with `format(Decimal.from_float(x), 'y')` as described [here](https://docs.python.org/3/tutorial/floatingpoint.html#representation-error) or is_close described [here](https://www.python.org/dev/peps/pep-0485/) and [here](http://docs.scipy.org/doc/numpy-dev/reference/generated/numpy.isclose.html)?

**Comment by wasade** [comment]
Three questions, what numpy types are being reported on each system, and
are there any type conversions being done (e.g., between python and numpy)
Second, are the values composing the r_i's really small or large in nature?
Third, same numpy versions and libraries being linked?

On Mon, Nov 16, 2015 at 12:41 AM, Will Van Treuren <notifications@github.com

**Comment by ElDeveloper** [comment]
I was thinking about the same thing, what about casting and forcing all
inputs to be of the same type maybe np.float64.

**Comment by antgonza** [comment]
Note that I don't think that forcing the type will work as the issue is the bits of precision and I'm not sure if there is a way to force them. Thus, the idea of going around either by using is_close or `format(Decimal.from_float(x), 'y')`

**Comment by wasade** [comment]
Unnecessary casting could lead to precision issues. Questions were oriented
to help understand the root cause of the issue

**Comment by ebolyen** [comment]
I think @antgonza is right, we would need to use something akin to `is_close`. Looking around, it isn't super unusual for linux to use extended precision registers while BSD variants stick to the natural width of the type. More here: https://randomascii.wordpress.com/2013/07/16/floating-point-determinism/

In particular, intermediate results do not have a defined width in IEEE or in C/C++

**Comment by wasade** [comment]
Is_close may be necessary, but am hoping to understand what the problem is.
It could standards issues but I don't think we've determined that is
actually the case?

If is_close just works, then its probably not worth a deeper investigation
though.

**Comment by antgonza** [comment]
@wasade if you compare @wdwvt1 initial report and the first link in my initial answer I think we are seeing the same problem, which they say is not a bug/issue but just something we need to deal with. However, @wdwvt1 can confirm. 

Link here: https://docs.python.org/3/tutorial/floatingpoint.html#representation-error

**Comment by wasade** [comment]
The difference in the failed test that is the seed of this thread is
substantial. Is_close on the test may lead to false confidence

**Comment by wdwvt1** [comment]
Hi all - thanks for the responses. 

I want to add a piece of information that confuses me (but likely because I just don't understand precision/floats well enough). If i take the `r_i`'s from the linux and mac builds, and I ask for their integer denominators (in powers of 2), I get the following values:
```python
linux_values = {45.0, 46.0, 49.0, 50.0, 51.0, 52.0, 53.0, 54.0, 55.0, 56.0, 57.0, 58.0, 59.0, 107.0}
mac_values = {44.0, 45.0, 47.0, 48.0, 49.0, 50.0, 51.0, 52.0, 53.0, 54.0, 55.0, 56.0, 57.0, 58.0, 59.0, 108.0}
```
Some of them are `long` type, but sadly the ones that are `long` type are not the ones that are causing unexpected comparisons. It does seem to suggest that different amounts of precision are being used, but how this is happening is very unclear to me. 

@wasade 
The numpy and scipy library versions are different, but we've seen repeated problems across various versions of numpy/scipy. I think that the failure needs to be demonstrated on the same versions of numpy/scipy to be sure. I can try to tackle that later this week.

I'll check the types that are being reported. Given the representation I am guessing both are `np.float64` but I need to check this. 

I don't believe there are type conversions being done, the values are just passed between numpy and scipy. 

The values are small, in the range [-1, 1]. The values that are failing the equality check are about .34. 

@antgonza 
I agree that I think the problem will not be solved by casting to `numpy.float64`. I think the `Decimal` module is a possible solution, but I think that we should be able to solve this problem with understanding the floats better. 

I can change the comparison of the underlying function to `is_close`, but this is worrisome to me because we should be getting exact comparisons that we don't have to worry about this with. In addition, every other bootstrapped test in the entire `qiime.otu_significance` module depends on the comparison function I'd be changing. I am wondering why none of the others fail, and it makes me uneasy to change the whole thing. Could just be dragging my feet though, happy to hear other opinions on this.
