### ISSUE TITLE
Memory issue in split_libraries.py

### ISSUE THREAD

**Issue by mortonjt** [biocore/qiime#2084]
Ran into a problem on the [qiime forum](https://groups.google.com/forum/#!topic/qiime-forum/DZvwHcz-Cts) about running out of memory when running split libraries.

From the moment before split_libraries.py was killed
```
              PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND 
248765 7456 qiime     20   0 11.9g 9.7g 1236 D  8.3 93.1  26:06.52 split_libraries
```
It looks like split_libraries.py is eating up ~12GB of memory.  So this looks like a memory issue

Here is another [post](https://groups.google.com/forum/#!topic/qiime-forum/a603iYjppB4) that had a similar problem.

I'm not sure why the memory requirements are so high.  Any ideas on how to resolve this?

**Comment by josenavas** [comment]
@walterst @wasade this is really surprising. Do you have any insight on why this is the case?

**Comment by walterst** [comment]
It's loading the qual scores into memory (https://github.com/biocore/qiime/blob/master/qiime/split_libraries.py#L1367) which is likely the culprit.

**Comment by josenavas** [comment]
:boom:

**Comment by walterst** [comment]
I think the original intended design was to allow for fasta/qual files that contained seqs that weren't necessarily in the same order (I don't know when this would happen though). I think it should parse through the two files (or single) file like the fastq parsing for reads/barcodes in split_libraries_fastq.py.

One could possibly work around this by splitting the input fasta/qual files into separate files, run split_libraries.py on these individually (adding a -n X command to get unique numbers).

This has been kicking around for a while-eventually, the universal 454/illumina parsing was going to be handled by a single script (and input reads/quals would be iterated through, rather than loaded into memory), right @wasade ?

**Comment by wasade** [comment]
We dropped it since qiime 1.9 is a dead end

**Comment by gregcaporaso** [comment]
This will be addressed in QIIME 2, when we completely re-write this processing pipeline.
