### ISSUE TITLE
What should I put in the Barcode and LinkerPrimer sequences in   QIIME Mapping file ?

### ISSUE THREAD

**Issue by SantoshThapa1** [biocore/qiime#2139]
Hello,

I'm continuously having trouble of run abort while trying to analyze my MiSeq data using QIIME Visualization App available on Miseq BaseSpace. The error reads "Error in make_emperor.py: None of your sample identifiers match between the mapping file and the coordinates file. Verify you are using a coordinates file and a mapping file that belong to the same dataset."

Can anyone help me to figure me out what's wrong with  my mapping file setup. 

(1) **BarcodeSequence:** What should I put in this column ? Is it the Nextera XT 5' Index Primer sequence (such as  the sequence for N724, Nxxx)  or a different one? 

(2) **LinkerPrimerSequence:** What should I put in this column ? 
Is it forward primer sequence (such as 515F  sequence GTGCCAGCMGCCGCGGTAA that I am using for my experiments) ?

Any suggestions in this matter would be appreciated.

Thanks,
Santosh

**Comment by ElDeveloper** [comment]
The problem you are experiencing is due to the names of your samples in
your mapping file, and in your OTU table not matching. There's a file in
the output of the "QIIME Preprocessing" app that has a summary of your
BIOM table, look for the sample identifiers listed there, they should
match one-to-one the sample identifiers (entries in the first column) of
your mapping file.

**Comment by SantoshThapa1** [comment]
Thank you for your help.

**Comment by genotipo** [comment]
Hello I am new in qiime so I decided take qiime basespace for the analysis of my dataset. Now I ask me about the why i can't see and read nothing in paper about qiime basespace. If i sent my report is acceptable public mi paper with basespace qiime?

**Comment by gregcaporaso** [comment]
Hi @genotipo, The BaseSpace QIIME application is newer than the QIIME paper, which is why it's not covered in there. It's fine to publish results generated with the QIIME BaseSpace app, as BaseSpace is just wrapping QIIME. You should cite the original QIIME Nature Methods paper, as well as the relevant citation for BaseSpace if one exists. @ElDeveloper, do you know how BaseSpace itself should be cited?

**Comment by genotipo** [comment]
Thanks it is really good new. Only I was asking,  because I am analysing my
dataset now for my PhD.  I was looking about the how basespace cited so I
know.

2016-04-14 14:27 GMT+02:00 Greg Caporaso <notifications@github.com>:

**Comment by ElDeveloper** [comment]
@gregcaporaso @genotipo, to the best of my knowledge there's no citation available for BaseSpace, but I think it's fine to just link to their main website. To add to @gregcaporaso's suggestion on citing QIIME: in BaseSpace there's a few tools being used that you should cite as they are used as part of the default pipeline:

- Greengenes: reference database. https://www.ncbi.nlm.nih.gov/pubmed/22134646
- uclust: clustering of sequences. https://www.ncbi.nlm.nih.gov/pubmed/20709691
- UniFrac: phylogenetic metric  https://www.ncbi.nlm.nih.gov/pubmed/16332807
- Faith's phylogenetic diversity: http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2674678/ (I think).
- Emperor: visualization of beta diversity plots. https://www.ncbi.nlm.nih.gov/pubmed/24280061

**Comment by genotipo** [comment]
Thanks you

**Comment by genotipo** [comment]
[image: Imágenes integradas 1]
Hello, I put running my samples 2 days ago, the numbers is 245 samples. Is
this normal?  because this is only a sub populations, the total samples is
754. Thanks you for your helps.

2016-04-14 14:27 GMT+02:00 Greg Caporaso <notifications@github.com>:

**Comment by ElDeveloper** [comment]
@genotipo, would you mind posting this question (including a little bit more information about the problem) to the QIIME forum:

https://groups.google.com/forum/#!forum/qiime-forum

**Comment by genotipo** [comment]
I ask in forum and nobody respond. I don't know if I need stop the analysis...

**Comment by genotipo** [comment]
Hello My run not finished yet, I am stressful because I connected with illumina support and they said me that ask in this forum. I tried put 10 samples, 20 samples, 30 samples, 40 samples and the run was good but when i try put 50 samples in the same time the program no finish. The problem is that in my lapton can't install qiime because isn't good lapton, it is a i3 with 4GB RAM and windows 32bits so the unique opcion is use qiime app basespace. Can Someone Help me? please
