### ISSUE TITLE
Qiime User Interface

### ISSUE THREAD

**Issue by patthehat033** [biocore/qiime#2184]
Hello,

As a school project, I am developing a Qiime User Interface in JAVA for Windows using SSH to access a virtualbox and run the scripts for Qiime.  This is currently for personal (educational) use.  However, when the application is finished, other Qiime users may also want to use it.  Is there certain standards and testing that would need to be done to release this to the users of Qiime? 

Thank you!

**Comment by gregcaporaso** [comment]
Hi @patthehat033, thanks for your interest in QIIME. You might want to look into doing this for [QIIME 2](https://qiime2.org), rather than for QIIME 1, as QIIME 2 is being developed with a software development kit to explicitly support third-part developers creating their own interfaces. Also, in January of 2018 we will stop supporting QIIME 1 in favor of only supporting QIIME 2, so that might factor into your decision. 

In either case (developing for QIIME 1 or QIIME 2), I would recommend that you confirm that all tests pass (unit tests, and in QIIME 1 the script usage tests), and that you can run through the *Moving Pictures Tutorial* as that provides a reasonable integration test. 

Hope this helps!

**Comment by rob-knight** [comment]
+1 on recommendation to target to qiime 2. This will ultimately be a lot more useful for users. Note also that we are in the process of overhauling the recommended workflow in the light of new developments (balance trees, deblur etc) so it might be useful to connect again in a couple of months. Thanks for your interest!



On Mar 29, 2017, at 10:22 AM, Greg Caporaso <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @patthehat033<https://github.com/patthehat033>, thanks for your interest in QIIME. You might want to look into doing this for QIIME 2<https://qiime2.org>, rather than for QIIME 1, as QIIME 2 is being developed with a software development kit to explicitly support third-part developers creating their own interfaces. Also, in January of 2018 we will stop supporting QIIME 1 in favor of only supporting QIIME 2, so that might factor into your decision.

In either case (developing for QIIME 1 or QIIME 2), I would recommend that you confirm that all tests pass (unit tests, and in QIIME 1 the script usage tests), and that you can run through the Moving Pictures Tutorial as that provides a reasonable integration test.

Hope this helps!

-

**Comment by patthehat033** [comment]
@gregcaporaso @rob-knight Thank you for both of your responses!  I navigated through the Qiime 2 link you guys provided.  Are the original scripts from Qiime 1 still supported on Qiime 2 if you use the terminal within a VirtualBox?

**Comment by gregcaporaso** [comment]
@patthehat033, the QIIME 1 scripts are not installed in the QIIME 2 virtual box, nor vice versa. QIIME 2 is a complete re-write of QIIME, and while many of the same methods exist or will exist, their interfaces are different. And as @rob-knight mentions, many methods have been replaced with more relevant, newer methods. 

While it is possible to install both side-by-side (in conda environments), if you want to wrap QIIME 1 scripts via a Virtual Box image, you'd have a much easier time doing that through the QIIME 1 Virtual Box. I can't stress enough though that you would have an easier time, and would produce something that would ultimately be used by more people, if you targeted QIIME 2 instead.

**Comment by patthehat033** [comment]
@gregcaporaso Thank you for the response.  Is there a Windows application that will be available for Qiime 2?  That is ultimately what I want to develop.  What would be the best approach for doing that? I could not seem to locate the SDK you mentioned in the above messages.

**Comment by jairideout** [comment]
@patthehat033, QIIME 2 does not currently support Windows. We don't have a timeline for when Windows support will be added. Are you required to develop a native Windows application? If not, it'll be easier to write a QIIME 2 GUI that's compatible with Linux, and then distribute that interface (along with QIIME 2) in a VirtualBox image that Windows users can install. If you decide to go this route, I can point you to some examples of the QIIME 2 SDK being used to build interfaces. QIIME 2 is still in alpha release phase and we don't have docs yet for the SDK.

If you're required to develop a native Windows application, that'll be a harder task to accomplish. You'll need to have QIIME 2 running in some sort of virtual machine, and have your native Windows GUI talk to that virtual machine. Here's the [virtual machine images we distribute](https://docs.qiime2.org/2017.2/install/virtual/). How you accomplish this communication between your Windows GUI and the virtual machine is pretty open-ended, and will also depend on what virtual machine technology you choose.

If you have more specific questions about developing an interface for QIIME 2, come [find us on Slack](https://docs.qiime2.org/2017.2/community/#slack-team-developers)!

**Comment by patthehat033** [comment]
@jairideout I am planning to develop a Windows application for Qiime because it is not currently supported, as you mentioned, and a lot of novice computer users have trouble with Linux but are familiar with Windows.  Most people who are using Qiime have probably become fairly experienced using Linux, but I think it could be very useful to have a Windows version floating around for anyone who wants to do biological research but lacks an understanding of Linux.  My original plan as you read above was to use SSH to communicate through the VirtualBox.  I had tested the idea on Qiime 1 and it actually worked quite well.  However, I agree with everyone that it would be more beneficial to create an application for Qiime 2.  I read through the Qiime 2 website and noticed that that a command line version of Qiime 2 is available.  Do you think it would be possible to still use SSH as means of communicating between the Windows instance and the Linux VirtualBox and run Qiime 2 commands through that?

**Comment by thermokarst** [comment]
@patthehat033, as @gregcaporaso [mentioned above](https://github.com/biocore/qiime/issues/2184#issuecomment-290160990), there is actually a QIIME 2 [Software Development Kit](https://github.com/qiime2/qiime2/tree/master/qiime2/sdk). We are still working on documentation for this aspect of the framework, but you can see an example of it being put to use in [QIIME 2 Studio](https://docs.qiime2.org/2017.2/interfaces/q2studio/). This is an [Electron-based](https://electron.atom.io/) User Interface for QIIME 2, which is technically supported on Windows. That is, the user interface (QIIME 2 Studio) should work on windows, we just haven't tackled getting the core QIIME 2 plugins (and the framework itself) tested and running on Windows. Maybe you would be interested in helping get Windows support for the Studio a reality? One option would be to use our [Docker image](https://docs.qiime2.org/2017.2/install/virtual/docker/) as a backend, and come up with a way to wire the Studio to Docker? SSH as a communication protocol between the GUI and the VM probably doesn't make a lot of sense in the QIIME 2 world, because we already have an SDK available (for example, [q2cli](https://github.com/qiime2/q2cli) and QIIME 2 Studio both use the same SDK to interact with the QIIME 2 framework (and all of the user's installed plugins), that way the same microbiome bioinformatics functionality is exposed everywhere.

As @jairideout mentioned above, we monitor [Slack](https://slack.qiime2.org) --- if you want to continue this discussion please find us there.

Thanks!
